import type { CrewMember, WatchSlot, WatchTemplate, Locale, RoleDefinition } from './types';

export const MAX_HISTORY_SIZE = 20;

function formatHour(hour: number): string {
  const h = hour === 24 ? 24 : hour % 24;
  return `${String(h).padStart(2, '0')}:00`;
}

function generateTimeSlots(
  startHour: number,
  slotDurationHours: number,
  slotCount: number,
  reqCrew: number,
): { start: string; end: string; reqCrew: number }[] {
  return Array.from({ length: slotCount }, (_, i) => ({
    start: formatHour(startHour + i * slotDurationHours),
    end: formatHour(startHour + (i + 1) * slotDurationHours),
    reqCrew,
  }));
}

export const ROLES: Record<string, RoleDefinition> = {
  CAPTAIN: { id: 'captain', label: 'Kapitan', icon: 'Shield', color: 'text-amber-500' },
  OFFICER: { id: 'officer', label: 'Oficer', icon: 'Anchor', color: 'text-sky-500' },
  SAILOR: { id: 'sailor', label: 'Żeglarz', icon: 'User', color: 'text-slate-500' },
  COOK: { id: 'cook', label: 'Kambuz (Perz)', icon: 'ChefHat', color: 'text-emerald-500' },
};

export const defaultCrew: CrewMember[] = [
  { id: 'c1', name: 'Anna', role: 'captain' },
  { id: 'c2', name: 'Michał', role: 'officer' },
  { id: 'c3', name: 'Kasia', role: 'sailor' },
  { id: 'c4', name: 'Tomek', role: 'sailor' },
  { id: 'c5', name: 'Piotr', role: 'cook' },
];

export const defaultSlots: WatchSlot[] = generateTimeSlots(0, 4, 6, 2).map((slot, i) => ({
  id: String(i + 1),
  ...slot,
}));

export const WATCH_TEMPLATES: Record<string, WatchTemplate> = {
  '6x4h': {
    nameKey: 'template.6x4h',
    descKey: 'template.6x4h.desc',
    minCrew: 3,
    optimalCrew: 6,
    slots: generateTimeSlots(0, 4, 6, 2),
  },
  '3x8h': {
    nameKey: 'template.3x8h',
    descKey: 'template.3x8h.desc',
    minCrew: 3,
    optimalCrew: 6,
    slots: generateTimeSlots(0, 8, 3, 2),
  },
  '4x6h': {
    nameKey: 'template.4x6h',
    descKey: 'template.4x6h.desc',
    minCrew: 4,
    optimalCrew: 8,
    slots: generateTimeSlots(0, 6, 4, 2),
  },
  '2x12h': {
    nameKey: 'template.2x12h',
    descKey: 'template.2x12h.desc',
    minCrew: 2,
    optimalCrew: 4,
    slots: generateTimeSlots(6, 12, 2, 2),
  },
  dog: {
    nameKey: 'template.dog',
    descKey: 'template.dog.desc',
    minCrew: 4,
    optimalCrew: 7,
    slots: [
      { start: '00:00', end: '04:00', reqCrew: 2 },
      { start: '04:00', end: '08:00', reqCrew: 2 },
      { start: '08:00', end: '12:00', reqCrew: 2 },
      { start: '12:00', end: '16:00', reqCrew: 2 },
      { start: '16:00', end: '18:00', reqCrew: 2 },
      { start: '18:00', end: '20:00', reqCrew: 2 },
      { start: '20:00', end: '24:00', reqCrew: 2 },
    ],
  },
  swedish: {
    nameKey: 'template.swedish',
    descKey: 'template.swedish.desc',
    minCrew: 3,
    optimalCrew: 5,
    slots: [
      { start: '00:00', end: '06:00', reqCrew: 2 },
      { start: '06:00', end: '12:00', reqCrew: 2 },
      { start: '12:00', end: '16:00', reqCrew: 2 },
      { start: '16:00', end: '20:00', reqCrew: 2 },
      { start: '20:00', end: '24:00', reqCrew: 2 },
    ],
  },
  '12x2h_racing': {
    nameKey: 'template.racing',
    descKey: 'template.racing.desc',
    minCrew: 6,
    optimalCrew: 8,
    slots: generateTimeSlots(0, 2, 12, 3),
  },
};

export const translations: Record<Locale, Record<string, string>> = {
  'pl-PL': {
    'role.captain': 'Kapitan',
    'role.officer': 'Oficer',
    'role.sailor': 'Żeglarz',
    'role.cook': 'Kambuz (Perz)',
    'tab.setup': 'Konfiguracja',
    'tab.schedule': 'Harmonogram',
    'tab.dashboard': 'Dashboard',
    'tab.gantt': 'Gantt',
    'tab.analytics': 'Analityka',
    'btn.generate': 'Generuj harmonogram wacht',
    'btn.print': 'Drukuj',
    'btn.export.pdf': 'PDF',
    'btn.share': 'Udostępnij',
    'btn.readonly': 'Tylko odczyt',
    'btn.qr': 'QR Kod',
    'btn.nightMode': 'Tryb nocny',
    'btn.undo': 'Cofnij',
    'btn.redo': 'Ponów',
    'btn.help': 'Pomoc',
    'btn.save': 'Zapisz',
    'btn.cancel': 'Anuluj',
    'btn.close': 'Zamknij',
    'btn.add': 'Dodaj',
    'btn.delete': 'Usuń',
    'btn.dogWatches': 'Dodaj Psie Wachty (16-20)',
    'btn.addSlot': 'Dodaj okno wachtowe',
    'btn.importConfig': 'Importuj konfigurację',
    'btn.exportConfig': 'Eksportuj konfigurację',
    'common.day': 'Dzień',
    'common.days': 'dni',
    'common.hours': 'godziny',
    'common.crew': 'Załoga',
    'common.schedule': 'Harmonogram',
    'common.statistics': 'Statystyki',
    'common.name': 'Imię',
    'common.role': 'Rola',
    'common.watches': 'Wachty',
    'common.date': 'Data',
    'common.time': 'Czas',
    'common.members': 'Członkowie',
    'common.people': 'osób',
    'common.person': 'osoba',
    'heading.fullSchedule': 'Pełny Harmonogram',
    'heading.crewAndRoles': 'Załoga i Role',
    'heading.watchSystem': 'System Wachtowy',
    'heading.cruiseSettings': 'Ustawienia Rejsu',
    'heading.allWatchTemplates': 'Wszystkie szablony systemów wachtowych',
    'heading.recommendedSystems': 'Rekomendowane systemy dla Twojego rejsu',
    'heading.crewStatistics': 'Statystyki Załogi',
    'heading.analytics': 'Panel Analityczny',
    'heading.ganttChart': 'Wykres Gantta - Widok Osi Czasu',
    'heading.help': 'Pomoc',
    'heading.keyboardShortcuts': 'Skróty klawiszowe',
    'label.startDate': 'Data startu (Dzień 1)',
    'label.duration': 'Czas trwania (dni)',
    'label.namePlaceholder': 'Imię...',
    'label.maxDuration': 'Max 60 dni dla tras oceanicznych',
    'label.crewLimit': '({current}/15)',
    'label.totalWatches': 'Liczba wacht',
    'label.totalHours': 'Ilość godzin',
    'label.nightWatches': 'Nocne wachty',
    'label.captainParticipates': 'Kapitan pełni wachty',
    'label.start': 'Start',
    'label.end': 'Koniec',
    'label.requiredCrew': 'Ilość osób',
    'label.action': 'Akcja',
    'label.crewMember': 'Członek załogi',
    'label.info': 'Info',
    'tip.dragDrop': 'Tip: Przeciągnij i upuść (Drag&Drop) osobę, aby zamienić ją miejscami.',
    'msg.best': 'Najlepszy',
    'msg.copied': 'Skopiowano!',
    'msg.loading': 'Ładowanie...',
    'msg.generating': 'Generuję harmonogram...',
    'msg.noSchedule': 'Brak wygenerowanego harmonogramu',
    'msg.generateFirst': 'Wygeneruj harmonogram, aby zobaczyć wykres Gantta',
    'msg.noData': 'Brak danych',
    'msg.endAfterStart': 'Czas końca wachty musi być później niż czas rozpoczęcia.',
    'msg.watchOverlap': 'Wachta nakłada się z inną wachtą. Sprawdź godziny.',
    'msg.dogWatchesApplied': 'Dodano psie wachty (16-18 i 18-20)',
    'msg.dogWatchesNotApplicable': 'Nie można dodać psich wacht. Wymaga wachty 16:00-20:00.',
    'msg.coverageGap': 'Luka w pokryciu',
    'msg.coverage24h': 'Pokrycie 24h',
    'msg.ganttInfo':
      'Ten wykres Gantta pokazuje przydzielone wachty dla wszystkich dni rejsu. Każdy kolorowy pasek reprezentuje okres wachty; najedź kursorem na pasek, aby zobaczyć dokładne godziny.',
    'analytics.totalWatches': 'Suma Wacht',
    'analytics.activeCrew': 'Aktywna Załoga',
    'analytics.totalDays': 'Wszystkie Dni',
    'analytics.avgHours': 'Śr. Godz./Osobę',
    'analytics.workloadDistribution': 'Rozkład Obciążenia',
    'analytics.mostHours': 'Najwięcej Godzin',
    'analytics.mostNightWatches': 'Najwięcej Wacht Nocnych',
    'aria.toggleNightMode': 'Włącz tryb nocny',
    'aria.disableNightMode': 'Wyłącz tryb nocny',
    'aria.shareEditableLink': 'Udostępnij link do edycji grafiku',
    'aria.shareReadonlyLink': 'Udostępnij link tylko do odczytu',
    'aria.shareQR': 'Udostępnij grafik przez kod QR',
    'aria.undoLastChange': 'Cofnij ostatnią zmianę',
    'aria.redoLastChange': 'Ponów ostatnią cofniętą zmianę',
    'aria.switchPolish': 'Przełącz na Polski',
    'aria.switchEnglish': 'Przełącz na Angielski',
    'aria.exportJSON': 'Eksportuj konfigurację załogi i wacht do JSON',
    'aria.importJSON': 'Importuj konfigurację załogi i wacht z JSON',
    'help.intro':
      'Witaj w aplikacji Wachtownik! Ta aplikacja pomaga w tworzeniu harmonogramów wacht dla załogi jachtu.',
    'help.step1': 'Skonfiguruj załogę - dodaj członków załogi i przypisz im role',
    'help.step2': 'Wybierz lub dostosuj system wachtowy',
    'help.step3': 'Kliknij "Generuj harmonogram wacht"',
    'help.step4': 'Eksportuj do PDF lub udostępnij przez link/QR kod',
    'template.6x4h': '6 wacht × 4h (tradycyjny)',
    'template.6x4h.desc': 'System tradycyjny - 6 wacht po 4 godziny',
    'template.3x8h': '3 wachty × 8h',
    'template.3x8h.desc': 'Długie wachty - 3 bloki po 8 godzin',
    'template.4x6h': '4 wachty × 6h',
    'template.4x6h.desc': 'Średnie wachty - 4 bloki po 6 godzin',
    'template.2x12h': '2 wachty × 12h',
    'template.2x12h.desc': 'Dzienna/nocna - 2 długie bloki po 12 godzin',
    'template.dog': 'Psie wachty (7 wacht)',
    'template.dog.desc': 'System z wachtami psimi 16-18 i 18-20',
    'template.swedish': 'System szwedzki (5 wacht)',
    'template.swedish.desc': '5 wacht: 2×6h + 3×4h',
    'template.racing': 'System regatowy (12 wacht × 2h)',
    'template.racing.desc': 'Krótkie, intensywne wachty dla regat',
    'template.traditional': 'tradycyjny',
    'template.traditional.desc': 'System tradycyjny - 6 wacht po 4 godziny',
    'template.long': 'Długie wachty',
    'template.long.desc': 'długie wachty - 3 bloki po 8 godzin',
    'tab.livePanel': 'Panel Nawigacyjny na Żywo',
    'msg.alarmOn': 'Alarm ON',
    'msg.alarmOff': 'Alarm OFF',
    'msg.noUpcomingWatches': 'Brak kolejnych wacht.',
    'label.cruiseProgress': 'Progres rejsu',
    'label.crewSize': 'Rozmiar załogi',
    'label.optimal': 'opt',
    'btn.addPerson': 'Dodaj osobę',
    'label.exemptFromWatches': 'Zwolniony z wacht',
    'label.day': 'Dzień',
    'heading.crewAndRolesWithLimit': 'Załoga i Role',
    'heading.summaryAndExport': 'Podsumowanie i Eksport',
    'heading.crewStatisticsExport': 'Statystyki Załogi',
    'label.upcomingWatch': 'Następni w kolejce',
    'heading.appTitle': 'Wachtownik',
    'title.backToMenu': 'OpenAnchor - Powrót do menu',
    'aria.backToMenu': 'Powrót do menu',
    'title.nightMode': 'Tryb Czerwonego Światła',
    'title.undo': 'Cofnij (Ctrl+Z)',
    'title.redo': 'Ponów (Ctrl+Y)',
  },
  'en-US': {
    'role.captain': 'Captain',
    'role.officer': 'Officer',
    'role.sailor': 'Sailor',
    'role.cook': 'Cook (Galley)',
    'tab.setup': 'Setup',
    'tab.schedule': 'Schedule',
    'tab.dashboard': 'Dashboard',
    'tab.gantt': 'Gantt',
    'tab.analytics': 'Analytics',
    'btn.generate': 'Generate watch schedule',
    'btn.print': 'Print',
    'btn.export.pdf': 'PDF',
    'btn.share': 'Share',
    'btn.readonly': 'Read-only',
    'btn.qr': 'QR Code',
    'btn.nightMode': 'Night mode',
    'btn.undo': 'Undo',
    'btn.redo': 'Redo',
    'btn.help': 'Help',
    'btn.save': 'Save',
    'btn.cancel': 'Cancel',
    'btn.close': 'Close',
    'btn.add': 'Add',
    'btn.delete': 'Delete',
    'btn.dogWatches': 'Add Dog Watches (16-20)',
    'btn.addSlot': 'Add watch slot',
    'btn.addPerson': 'Add person',
    'btn.importConfig': 'Import configuration',
    'btn.exportConfig': 'Export configuration',
    'common.day': 'Day',
    'common.days': 'days',
    'common.hours': 'hours',
    'common.crew': 'Crew',
    'common.schedule': 'Schedule',
    'common.statistics': 'Statistics',
    'common.name': 'Name',
    'common.role': 'Role',
    'common.watches': 'Watches',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.members': 'Members',
    'common.people': 'people',
    'common.person': 'person',
    'heading.fullSchedule': 'Full Schedule',
    'heading.crewAndRoles': 'Crew and Roles',
    'heading.watchSystem': 'Watch System',
    'heading.cruiseSettings': 'Cruise Settings',
    'heading.allWatchTemplates': 'All watch system templates',
    'heading.recommendedSystems': 'Recommended systems for your cruise',
    'heading.crewStatistics': 'Crew Statistics',
    'heading.analytics': 'Analytics Dashboard',
    'heading.ganttChart': 'Gantt Chart - Timeline View',
    'heading.help': 'Help',
    'heading.keyboardShortcuts': 'Keyboard Shortcuts',
    'label.startDate': 'Start date (Day 1)',
    'label.duration': 'Duration (days)',
    'label.namePlaceholder': 'Name...',
    'label.maxDuration': 'Max 60 days for oceanic routes',
    'label.crewLimit': '({current}/15)',
    'label.totalWatches': 'Total watches',
    'label.totalHours': 'Total hours',
    'label.nightWatches': 'Night watches',
    'label.captainParticipates': 'Captain stands watches',
    'label.start': 'Start',
    'label.end': 'End',
    'label.requiredCrew': 'Required crew',
    'label.action': 'Action',
    'label.crewMember': 'Crew Member',
    'label.info': 'Info',
    'tip.dragDrop': 'Tip: Drag and drop a person to swap positions.',
    'msg.best': 'Best',
    'msg.copied': 'Copied!',
    'msg.loading': 'Loading...',
    'msg.generating': 'Generating schedule...',
    'msg.noSchedule': 'No generated schedule',
    'msg.generateFirst': 'Generate a schedule to see the Gantt chart',
    'msg.noData': 'No data',
    'msg.endAfterStart': 'End time must be after start time.',
    'msg.watchOverlap': 'Watch overlaps with another watch. Check the times.',
    'msg.dogWatchesApplied': 'Dog watches added (16-18 and 18-20)',
    'msg.dogWatchesNotApplicable': 'Cannot add dog watches. Requires a 16:00-20:00 watch.',
    'msg.coverageGap': 'Coverage gap',
    'msg.coverage24h': '24h coverage',
    'msg.ganttInfo':
      'This Gantt chart shows watch assignments for all days of the cruise. Each colored bar represents a watch period; hover over a bar to see exact times.',
    'analytics.totalWatches': 'Total Watches',
    'analytics.activeCrew': 'Active Crew',
    'analytics.totalDays': 'Total Days',
    'analytics.avgHours': 'Avg Hours/Person',
    'analytics.workloadDistribution': 'Workload Distribution',
    'analytics.mostHours': 'Most Hours',
    'analytics.mostNightWatches': 'Most Night Watches',
    'aria.toggleNightMode': 'Enable night mode',
    'aria.disableNightMode': 'Disable night mode',
    'aria.shareEditableLink': 'Share editable schedule link',
    'aria.shareReadonlyLink': 'Share read-only link',
    'aria.shareQR': 'Share schedule via QR code',
    'aria.undoLastChange': 'Undo last change',
    'aria.redoLastChange': 'Redo last undone change',
    'aria.switchPolish': 'Switch to Polish',
    'aria.switchEnglish': 'Switch to English',
    'aria.exportJSON': 'Export crew and watch configuration to JSON',
    'aria.importJSON': 'Import crew and watch configuration from JSON',
    'help.intro': 'Welcome to Wachtownik! This app helps create watch schedules for yacht crews.',
    'help.step1': 'Configure crew - add crew members and assign roles',
    'help.step2': 'Select or customize watch system',
    'help.step3': 'Click "Generate watch schedule"',
    'help.step4': 'Export to PDF or share via link/QR code',
    'template.6x4h': '6 watches × 4h (traditional)',
    'template.6x4h.desc': 'Traditional system - 6 watches of 4 hours each',
    'template.3x8h': '3 watches × 8h',
    'template.3x8h.desc': 'Long watches - 3 blocks of 8 hours each',
    'template.4x6h': '4 watches × 6h',
    'template.4x6h.desc': 'Medium watches - 4 blocks of 6 hours each',
    'template.2x12h': '2 watches × 12h',
    'template.2x12h.desc': 'Day/Night - 2 long blocks of 12 hours each',
    'template.dog': 'Dog watches (7 watches)',
    'template.dog.desc': 'System with dog watches 16-18 and 18-20',
    'template.swedish': 'Swedish system (5 watches)',
    'template.swedish.desc': '5 watches: 2×6h + 3×4h',
    'template.racing': 'Racing system (12 watches × 2h)',
    'template.racing.desc': 'Short, intensive watches for racing',
    'template.traditional': 'traditional',
    'template.traditional.desc': 'Traditional system - 6 watches of 4 hours each',
    'template.long': 'Long watches',
    'template.long.desc': 'Long watches - 3 blocks of 8 hours each',
    'tab.livePanel': 'Live Navigation Panel',
    'msg.alarmOn': 'Alarm ON',
    'msg.alarmOff': 'Alarm OFF',
    'msg.noUpcomingWatches': 'No upcoming watches.',
    'label.cruiseProgress': 'Cruise Progress',
    'label.crewSize': 'Crew Size',
    'label.optimal': 'opt',
    'label.exemptFromWatches': 'Exempt from watches',
    'label.day': 'Day',
    'heading.crewAndRolesWithLimit': 'Crew and Roles',
    'heading.summaryAndExport': 'Summary and Export',
    'heading.crewStatisticsExport': 'Crew Statistics',
    'label.upcomingWatch': 'Up Next',
    'heading.appTitle': 'Watch Planner',
    'title.backToMenu': 'OpenAnchor - Back to menu',
    'aria.backToMenu': 'Back to menu',
    'title.nightMode': 'Red Light Mode',
    'title.undo': 'Undo (Ctrl+Z)',
    'title.redo': 'Redo (Ctrl+Y)',
  },
};

export function t(key: string, locale: Locale = 'pl-PL'): string {
  return translations[locale]?.[key] || translations['pl-PL']?.[key] || key;
}
